version: '3.8'
services:
  api:
    build: ./backend
    container_name: nest-api
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nestapp

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
